openapi: 3.0.1
info:
  title: inventory.proto
  version: version not set
servers:
- url: /
paths:
  /inventory.Inventory/AdjustQty:
    post:
      operationId: Inventory_AdjustQty
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryAdjustQtyRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryStockItem'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/AdjustQtyCommitted:
    post:
      operationId: Inventory_AdjustQtyCommitted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryAdjustQtyCommittedRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryStockItem'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: adjust operations are intended for increment/decrement quantities fields
        by a certain amount
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/CreateStockItem:
    post:
      operationId: Inventory_CreateStockItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryCreateStockItemRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryStockItem'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/GetQtySalable:
    post:
      operationId: Inventory_GetQtySalable
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryGetQtySalableRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryGetQtySalableResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/GetStockItem:
    post:
      operationId: Inventory_GetStockItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryGetStockItemRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryStockItem'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/ListStockItems:
    post:
      operationId: Inventory_ListStockItems
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryListStockItemsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryListStockItemsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/ListStockItemsBySkus:
    post:
      operationId: Inventory_ListStockItemsBySkus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryListStockItemsBySkusRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryListStockItemsBySkusResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/RebalanceStockQtys:
    post:
      operationId: Inventory_RebalanceStockQtys
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryRebalanceStockQtysRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryStockItem'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: rebalance operation is intended for apply or discard a certain amount
        of qty_committed to qty and old qty_committed
      tags:
      - Inventory
      x-codegen-request-body-name: body
  /inventory.Inventory/UpdateStockItem:
    post:
      operationId: Inventory_UpdateStockItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventoryUpdateStockItemRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventoryStockItem'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Inventory
      x-codegen-request-body-name: body
components:
  schemas:
    UpdateStockItemRequestPayload:
      properties:
        outOfStockThreshold:
          format: int32
          type: integer
        qty:
          format: int32
          type: integer
        qtyCommitted:
          format: int32
          type: integer
      type: object
    inventoryAdjustQtyCommittedRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
        qtyAdjust:
          format: int32
          type: integer
      type: object
    inventoryAdjustQtyRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
        qtyAdjust:
          format: int32
          type: integer
      type: object
    inventoryCreateStockItemRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
        outOfStockThreshold:
          format: int32
          type: integer
        qty:
          format: int32
          type: integer
        qtyCommitted:
          format: int32
          type: integer
      type: object
    inventoryGetQtySalableRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
      type: object
    inventoryGetQtySalableResponse:
      example:
        qtySalable: 0
        tenantId: tenantId
        id: id
        sku: sku
      properties:
        tenantId:
          type: string
        id:
          type: string
        sku:
          type: string
        qtySalable:
          format: int32
          type: integer
      type: object
    inventoryGetStockItemRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
      type: object
    inventoryListStockItemsBySkusRequest:
      properties:
        tenantId:
          type: string
        skus:
          items:
            type: string
          type: array
      type: object
    inventoryListStockItemsBySkusResponse:
      example:
        stockItems:
        - outOfStockThreshold: 0
          createdAt: 2000-01-23T04:56:07.000+00:00
          qtyCommitted: 1
          qty: 6
          tenantId: tenantId
          id: id
          sku: sku
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - outOfStockThreshold: 0
          createdAt: 2000-01-23T04:56:07.000+00:00
          qtyCommitted: 1
          qty: 6
          tenantId: tenantId
          id: id
          sku: sku
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        stockItems:
          items:
            $ref: '#/components/schemas/inventoryStockItem'
          type: array
      type: object
    inventoryListStockItemsRequest:
      properties:
        tenantId:
          type: string
        pageSize:
          description: The maximum number of items to return.
          format: int64
          type: integer
        pageToken:
          description: "The next_page_token value returned from a previous List request,\
            \ if any."
          type: string
      type: object
    inventoryListStockItemsResponse:
      example:
        stockItems:
        - outOfStockThreshold: 0
          createdAt: 2000-01-23T04:56:07.000+00:00
          qtyCommitted: 1
          qty: 6
          tenantId: tenantId
          id: id
          sku: sku
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - outOfStockThreshold: 0
          createdAt: 2000-01-23T04:56:07.000+00:00
          qtyCommitted: 1
          qty: 6
          tenantId: tenantId
          id: id
          sku: sku
          updatedAt: 2000-01-23T04:56:07.000+00:00
        nextPageToken: nextPageToken
      properties:
        stockItems:
          items:
            $ref: '#/components/schemas/inventoryStockItem'
          type: array
        nextPageToken:
          description: |-
            Token to retrieve the next page of results, or empty if there are no
            more results in the list.
          type: string
      type: object
    inventoryRebalanceStockQtysRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
        qtyCommitted:
          format: int32
          type: integer
      type: object
    inventoryStockItem:
      example:
        outOfStockThreshold: 0
        createdAt: 2000-01-23T04:56:07.000+00:00
        qtyCommitted: 1
        qty: 6
        tenantId: tenantId
        id: id
        sku: sku
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        tenantId:
          type: string
        id:
          type: string
        sku:
          type: string
        outOfStockThreshold:
          format: int32
          type: integer
        qty:
          format: int32
          type: integer
        qtyCommitted:
          format: int32
          type: integer
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      type: object
    inventoryUpdateStockItemRequest:
      properties:
        tenantId:
          type: string
        sku:
          type: string
        payload:
          $ref: '#/components/schemas/UpdateStockItemRequestPayload'
        payloadMask:
          items:
            type: string
          type: array
      type: object
    protobufAny:
      properties:
        typeUrl:
          type: string
        value:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
      type: object
    rpcStatus:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
      type: object
x-original-swagger-version: "2.0"
